version: '3'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network

  chatbox:
    build: .
    container_name: chatbox
    depends_on:
      - ollama
    ports:
      - "31131:5000"
    volumes:
      - .:/app 
      # - ./db:/app/db
    networks:
      - ai-network
    restart: on-failure

volumes:
  ollama_data:

networks:
  ai-network:
    driver: bridge