version: '3'
services:
  chatbox:
    build: .
    container_name: chatbox
    ports:
      - "31131:5000"
    volumes:
      - ./db:/app/db
    networks:
      - ai-network
    restart: on-failure

networks:
  ai-network:
    driver: bridge