services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC (opsional)
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ollama-net

volumes:
  pip_cache:
  qdrant_data:

networks:
  ollama-net:
    external: true
