version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    # command: bash -c "ollama pull pnm-mistral && ollama serve"

  flask_app:
    build: .
    container_name: langchain-flask
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
      - ./docs:/app/docs
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama:
